exports.compositoresPage = (compositores,d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="stylesheet" href="./extras/w3.css"/>
        <title>Compositores</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-teal">
                <h1>Lista de compositores
                <a class ="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                <a class ="w3-btn w3-round w3-grey" href="/periodos">Períodos</a>
                </h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>Nome</th>
                        <th>Período</th>
                        <th></th>
                    </tr>`
    for(let i = 0; i < compositores.length; i++){
        pagHTML += `
                    <tr>
                        <td><a href="compositores/${compositores[i].id}">${compositores[i].nome}</a></td>
                        <td>${compositores[i].periodo}</td>
                        <td><a href="compositores/delete/${compositores[i].id}"><i>[Delete]</i></a>  <a href="compositores/edit/${compositores[i].id}"><i>[Edit]</i></a></td>
                    </tr>`
    }
        pagHTML += `            
                </table>   
            </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}


exports.periodosPage = (periodos,d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="stylesheet" href="./extras/w3.css"/>
        <title>Períodos</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-teal">
                <h1>Lista de períodos
                <a class ="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                <a class ="w3-btn w3-round w3-grey" href="/compositores">Compositores</a>
                </h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>Nome</th>
                        <th></th>
                    </tr>`
    for(let i = 0; i < periodos.length; i++){
        pagHTML += `
                    <tr>
                        <td><a href="periodos/${periodos[i].id}">${periodos[i].nome}</a></td>
                        <td><a href="periodos/delete/${periodos[i].id}"><i>[Delete]</i></a>  <a href="periodos/edit/${periodos[i].id}"><i>[Edit]</i></a></td>
                    </tr>`
    }
        pagHTML += `            
                </table>   
            </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}


exports.compositorPage = (compositor,d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="stylesheet" href="./extras/w3.css"/>
        <title>${compositor.nome}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-teal">
                <h1>${compositor.nome}</h1>
            </header>
            <div class="w3-container">
                <p><b>Data de Nascimento: </b>${compositor.dataNasc}</p>
                <p><b>Data de Óbito: </b>${compositor.dataObito}</p>
                <p><b>Período: </b>${compositor.periodo}</p>
                <p><b>Bio: </b>${compositor.bio}</p>
            </div>
            <br>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}




exports.periodoPage = (periodo,d,compositores) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="stylesheet" href="./extras/w3.css"/>
        <title>${periodo.nome}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-teal">
                <h1>${periodo.nome}</h1>
            </header>
            <div class="w3-container">`
                for(let i = 0; i < compositores.length; i++){
                    if(compositores[i].periodo == periodo.nome)
                        pagHTML += `<p>${compositores[i].nome}</p>`
                }
        pagHTML += `
            </div>
            <br>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}


exports.compositorForm = function(periodos, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="./extras/w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                <fieldset>
                    <legend>Metadata</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id"/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome"/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc"/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito"/>
                    <label>Período</label>
                    <select class="w3-input w3-round" name="periodo">${periodos.map(periodo => `<option value="${periodo.nome}">${periodo.nome}</option>`).join('')}</select>
                    <label>Bio</label>
                    <input class="w3-input w3-round" type="text" name="bio"/>
                </fieldset>

                    
                    <br/>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Register</button>

                </form>
                <br/>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}




exports.periodoForm = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="./extras/w3.css"/>
            <title>Período Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                <fieldset>
                    <legend>Metadata</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id"/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome"/>
                </fieldset>

                    <br/>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Register</button>

                </form>
                <br/>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}


exports.compositorFormEdit = function(compositor, periodos, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>${compositor.nome}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${compositor.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${compositor.nome}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${compositor.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${compositor.dataObito}"/>
                        <label>Período</label>
                        <select class="w3-input w3-round" name="periodo">${periodos.map(periodo => `<option value="${periodo.nome}">${periodo.nome}</option>`).join('')}</select>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${compositor.bio}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Submit Changes</button>
                </form>
                <br/>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}


exports.periodoFormEdit = function(periodo, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>${periodo.nome}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Período Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${periodo.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${periodo.nome}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Submit Changes</button>
                </form>
                <br/>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}